#!/usr/bin/env python

import re
import subprocess

process = subprocess.run(["nordvpn", "status"], check=True, stdout=subprocess.PIPE, universal_newlines=True)
status= process.stdout


if re.search('Connected', status):
    city = re.findall(r'City: (\w+)', status)[0]
    country = re.findall(r'Country: (\w+)', status)[0]
    ip = re.findall(r'IP. (\d+\.\d+\.\d+\.\d+)', status)[0]

    nordvpn=country+" » "+city+" » "+ip
else:
    nordvpn='Déconnecté'

print(nordvpn)
