#!/usr/bin/env bash
WHITE='\033[1;37m'
CYAN='\033[0;36m'
BLACK='\033[1;30m'
NC='\033[0m'


os=`lsb_release -is`
kernel=`uname -r`
uptime=`uptime -p | sed s/up\ //`
packages=`pacman -Qq | wc -l`
s=`$SHELL --version` ; shell=${s/\(*\)} 
resolution=`xrandr|grep "Screen 0" |awk -F", " '{print $2}' | sed "s/current //"`
while IFS=":" read -r a b; do
                case $a in
                    "MemTotal") ((mem_used+=${b/kB})); mem_total="${b/kB}" ;;
                    "Shmem") ((mem_used+=${b/kB}))  ;;
                    "MemFree" | "Buffers" | "Cached" | "SReclaimable")
                        mem_used="$((mem_used-=${b/kB}))"
                    ;;
                esac
            done < /proc/meminfo

            mem_used="$((mem_used / 1024))MiB"
            mem_total="$((mem_total / 1024))MiB"


printf "${WHITE}                    ${BLACK}   lomig${WHITE}@${BLACK}pennsardin\n" 
printf "${WHITE}         @             ----------------\n"
printf "${WHITE}        @@@         ${CYAN}   OS : ${NC}$os\n" 
printf "${WHITE}     @   @   @      ${CYAN}   Kernel : ${NC}$kernel\n"
printf "${WHITE}    @@@     @@@     ${CYAN}   Uptime : ${NC}$uptime\n"
printf "${WHITE}     @   @   @      ${CYAN}   Packages : ${NC}$packages\n"
printf "${WHITE}        /@\         ${CYAN}   Shell : ${NC}$shell\n"
printf "${WHITE}        @@@         ${CYAN}   Window Manager : ${NC}bspwm\n"
printf "${WHITE}       /@@@\        ${CYAN}   Resolution : ${NC}$resolution\n"
printf "${WHITE}       @@@@@        ${CYAN}   Terminal : ${NC}termite\n"
printf "${WHITE}      /@@@@@\       ${CYAN}   CPU : ${NC}AMD Ryzen 5 1500X @4Ghz\n"
printf "${WHITE}      \@@@@@/       ${CYAN}   GPU : ${NC}AMD Radeon RX 580\n"
printf "${WHITE}       \/ \/        ${CYAN}   Memory : ${NC}$mem_used / $mem_total\n"
echo ""

cs-panes

