#! /bin/sh

export DISPLAY=0
sxhkd &
setxkbmap fr bepo
#compton -cC -i 0.8 -e 0.8 -m 0.8 -r 4 -l -4 -t -4 &
sh ~/.fehbg &

polybar main &


bspc monitor  DisplayPort-1 -d I II III IV V VI VII
bspc monitor  DisplayPort-0 -d VIII
bspc monitor  HDMI-A-0 -d IX

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Firefox desktop='^5'

