#!/bin/bash

###
#
# Script do test an iso file temporarily
#
# The qcow2 disk is always formated first
# So dont launch this if you want to keep installation
# Or clone disk before re-use
#
###

QEMU="$HOME/qemu"

function img_create(){
    qemu-img create -f qcow2 $QEMU/img/test.img.qcow2 20G &> /dev/null
}

function install(){
    qemu-system-x86_64 -enable-kvm \
                       -smp 4 \
                       -k fr \
                       -m 2048 \
                       -hda $QEMU/img/test.img.qcow2 \
                       -boot d \
                       -cdrom "$1" \
                       -net nic \
                       -net user \
                       -usb \
                       -device usb-mouse \
                       -device usb-kbd \
                       -display gtk,show-cursor=on \
}

function launch(){
	qemu-system-x86_64 -enable-kvm \
			       	   -smp 4 \
                       -k fr \
                   	   -m 2048 \
                       -hda $QEMU/img/test.img.qcow2 \
                       -net nic \
                       -net user \
                       -usb \
                       -device usb-mouse \
                       -device usb-kbd \
                       -display gtk,show-cursor=on \
}

if [ ! -z "$1" ]
then
    if [ "${1##*.}" = "iso" ] && [ -f "$1" ]
    then
        img_create
        install $1
		launch
    fi
else
    echo "Please specify an iso image"
fi
